const adminRule = '@request.auth.collectionName = "admins" && @request.auth.active = true';
const publishedRule = "published = true";
const sectorPublishedRule = "sector.published = true";
const projectPublishedRule = "project.published = true";

const textField = (name: string, options: Record<string, unknown> = {}) => ({
  name,
  type: "text",
  ...options,
});

const boolField = (name: string, options: Record<string, unknown> = {}) => ({
  name,
  type: "bool",
  ...options,
});

const numberField = (name: string, options: Record<string, unknown> = {}) => ({
  name,
  type: "number",
  onlyInt: true,
  ...options,
});

const relationField = (name: string, collectionId: string, options: Record<string, unknown> = {}) => ({
  name,
  type: "relation",
  collectionId,
  maxSelect: 1,
  ...options,
});

export const pocketbaseSchema = [
  {
    name: "admins",
    type: "auth",
    authRule: "active = true",
    manageRule: adminRule,
    listRule: adminRule,
    viewRule: adminRule,
    createRule: adminRule,
    updateRule: adminRule,
    deleteRule: adminRule,
    passwordAuth: {
      enabled: true,
      identityFields: ["email"],
    },
    fields: [textField("name"), boolField("active")],
    indexes: ["CREATE UNIQUE INDEX idx_admins_email ON admins (email)"],
  },
  {
    name: "media_assets",
    type: "base",
    listRule: adminRule,
    viewRule: adminRule,
    createRule: adminRule,
    updateRule: adminRule,
    deleteRule: adminRule,
    fields: [
      textField("publicUrl", { required: true, max: 2048 }),
      textField("objectKey", { max: 2048 }),
      textField("bucket", { max: 255 }),
      textField("mimeType", { max: 255 }),
      numberField("size"),
      textField("altText", { max: 500 }),
      textField("source", { required: true, max: 20 }),
    ],
    indexes: ["CREATE UNIQUE INDEX idx_media_assets_public_url ON media_assets (publicUrl)"],
  },
  {
    name: "sectors",
    type: "base",
    listRule: publishedRule,
    viewRule: publishedRule,
    createRule: adminRule,
    updateRule: adminRule,
    deleteRule: adminRule,
    fields: [
      textField("slug", { required: true, max: 255 }),
      numberField("sortOrder"),
      boolField("published"),
      textField("name", { required: true, max: 255 }),
      textField("tagline", { max: 500 }),
      textField("heroImageUrl", { max: 2048 }),
      textField("imageUrl", { max: 2048 }),
      textField("seoTitle", { max: 255 }),
      textField("seoDescription", { max: 500 }),
      textField("ctaTitle", { max: 255 }),
      textField("ctaDescription", { max: 1000 }),
      textField("officerName", { max: 255 }),
      textField("officerTitle", { max: 255 }),
      textField("officerSpecialization", { max: 255 }),
      textField("officerPhone", { max: 255 }),
      textField("officerEmail", { max: 255 }),
      textField("officerImageUrl", { max: 2048 }),
      textField("consultationLink", { max: 2048 }),
      textField("reportLink", { max: 2048 }),
      textField("officerDescription", { max: 4000 }),
    ],
    indexes: ["CREATE UNIQUE INDEX idx_sectors_slug ON sectors (slug)"],
  },
  {
    name: "sector_overview_paragraphs",
    type: "base",
    listRule: sectorPublishedRule,
    viewRule: sectorPublishedRule,
    createRule: adminRule,
    updateRule: adminRule,
    deleteRule: adminRule,
    fields: [
      relationField("sector", "sectors", { required: true, minSelect: 1, cascadeDelete: true }),
      textField("value", { required: true, max: 4000 }),
      numberField("sortOrder"),
    ],
  },
  {
    name: "sector_stats",
    type: "base",
    listRule: sectorPublishedRule,
    viewRule: sectorPublishedRule,
    createRule: adminRule,
    updateRule: adminRule,
    deleteRule: adminRule,
    fields: [
      relationField("sector", "sectors", { required: true, minSelect: 1, cascadeDelete: true }),
      textField("label", { required: true, max: 255 }),
      textField("value", { required: true, max: 255 }),
      numberField("sortOrder"),
    ],
  },
  {
    name: "sector_why_invest",
    type: "base",
    listRule: sectorPublishedRule,
    viewRule: sectorPublishedRule,
    createRule: adminRule,
    updateRule: adminRule,
    deleteRule: adminRule,
    fields: [
      relationField("sector", "sectors", { required: true, minSelect: 1, cascadeDelete: true }),
      textField("value", { required: true, max: 4000 }),
      numberField("sortOrder"),
    ],
  },
  {
    name: "sector_advantages",
    type: "base",
    listRule: sectorPublishedRule,
    viewRule: sectorPublishedRule,
    createRule: adminRule,
    updateRule: adminRule,
    deleteRule: adminRule,
    fields: [
      relationField("sector", "sectors", { required: true, minSelect: 1, cascadeDelete: true }),
      textField("value", { required: true, max: 4000 }),
      numberField("sortOrder"),
    ],
  },
  {
    name: "projects",
    type: "base",
    listRule: publishedRule,
    viewRule: publishedRule,
    createRule: adminRule,
    updateRule: adminRule,
    deleteRule: adminRule,
    fields: [
      textField("legacyId", { required: true, max: 255 }),
      textField("slug", { required: true, max: 255 }),
      relationField("sector", "sectors", { required: true, minSelect: 1, cascadeDelete: true }),
      numberField("sortOrder"),
      boolField("published"),
      textField("type", { max: 255 }),
      textField("title", { required: true, max: 255 }),
      textField("subTitle", { max: 500 }),
      textField("description", { max: 8000 }),
      textField("brochureUrl", { max: 2048 }),
      textField("moreInfoUrl", { max: 2048 }),
      textField("videoUrl", { max: 2048 }),
      textField("heroVideoUrl", { max: 2048 }),
    ],
    indexes: [
      "CREATE UNIQUE INDEX idx_projects_slug ON projects (slug)",
      "CREATE UNIQUE INDEX idx_projects_legacy_id ON projects (legacyId)",
    ],
  },
  {
    name: "project_media",
    type: "base",
    listRule: projectPublishedRule,
    viewRule: projectPublishedRule,
    createRule: adminRule,
    updateRule: adminRule,
    deleteRule: adminRule,
    fields: [
      relationField("project", "projects", { required: true, minSelect: 1, cascadeDelete: true }),
      textField("url", { required: true, max: 2048 }),
      textField("altText", { max: 500 }),
      numberField("sortOrder"),
    ],
  },
  {
    name: "project_stats",
    type: "base",
    listRule: projectPublishedRule,
    viewRule: projectPublishedRule,
    createRule: adminRule,
    updateRule: adminRule,
    deleteRule: adminRule,
    fields: [
      relationField("project", "projects", { required: true, minSelect: 1, cascadeDelete: true }),
      textField("label", { required: true, max: 255 }),
      textField("value", { required: true, max: 255 }),
      numberField("sortOrder"),
    ],
  },
  {
    name: "project_highlights",
    type: "base",
    listRule: projectPublishedRule,
    viewRule: projectPublishedRule,
    createRule: adminRule,
    updateRule: adminRule,
    deleteRule: adminRule,
    fields: [
      relationField("project", "projects", { required: true, minSelect: 1, cascadeDelete: true }),
      textField("value", { required: true, max: 4000 }),
      numberField("sortOrder"),
    ],
  },
  {
    name: "project_financial_items",
    type: "base",
    listRule: projectPublishedRule,
    viewRule: projectPublishedRule,
    createRule: adminRule,
    updateRule: adminRule,
    deleteRule: adminRule,
    fields: [
      relationField("project", "projects", { required: true, minSelect: 1, cascadeDelete: true }),
      textField("value", { required: true, max: 4000 }),
      numberField("sortOrder"),
    ],
  },
  {
    name: "speaker_section_settings",
    type: "base",
    listRule: "",
    viewRule: "",
    createRule: adminRule,
    updateRule: adminRule,
    deleteRule: adminRule,
    fields: [
      textField("key", { required: true, max: 255 }),
      textField("title", { required: true, max: 255 }),
      textField("subtitle", { max: 500 }),
    ],
    indexes: ["CREATE UNIQUE INDEX idx_speaker_section_settings_key ON speaker_section_settings (key)"],
  },
  {
    name: "speaker_sessions",
    type: "base",
    listRule: "",
    viewRule: "",
    createRule: adminRule,
    updateRule: adminRule,
    deleteRule: adminRule,
    fields: [textField("name", { required: true, max: 255 }), numberField("sortOrder")],
  },
  {
    name: "speakers",
    type: "base",
    listRule: "",
    viewRule: "",
    createRule: adminRule,
    updateRule: adminRule,
    deleteRule: adminRule,
    fields: [
      relationField("session", "speaker_sessions", {
        required: true,
        minSelect: 1,
        cascadeDelete: true,
      }),
      textField("name", { required: true, max: 255 }),
      textField("title", { max: 255 }),
      textField("company", { max: 255 }),
      textField("imageUrl", { max: 2048 }),
      textField("alt", { max: 255 }),
      numberField("sortOrder"),
    ],
  },
] as const;
